# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: drrobot.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'drrobot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdrrobot.proto\x12\x07\x64rrobot\".\n\x0cWaterRequest\x12\r\n\x05state\x18\x01 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x02 \x01(\t\"\xb9\x01\n\rWaterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08\x65ndpoint\x18\x02 \x01(\t\x12\x14\n\x0cresponseTime\x18\x03 \x01(\t\x12\x12\n\nstatusCode\x18\x04 \x01(\x05\x12.\n\x04\x64\x61ta\x18\x05 \x03(\x0b\x32 .drrobot.WaterResponse.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32L\n\x0b\x44octorRobot\x12=\n\x0cPredictWater\x12\x15.drrobot.WaterRequest\x1a\x16.drrobot.WaterResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'drrobot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WATERRESPONSE_DATAENTRY']._loaded_options = None
  _globals['_WATERRESPONSE_DATAENTRY']._serialized_options = b'8\001'
  _globals['_WATERREQUEST']._serialized_start=26
  _globals['_WATERREQUEST']._serialized_end=72
  _globals['_WATERRESPONSE']._serialized_start=75
  _globals['_WATERRESPONSE']._serialized_end=260
  _globals['_WATERRESPONSE_DATAENTRY']._serialized_start=217
  _globals['_WATERRESPONSE_DATAENTRY']._serialized_end=260
  _globals['_DOCTORROBOT']._serialized_start=262
  _globals['_DOCTORROBOT']._serialized_end=338
# @@protoc_insertion_point(module_scope)
