# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: drrobot.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'drrobot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdrrobot.proto\x12\x07\x64rrobot\"0\n\x0b\x43hatRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\".\n\x0cWaterRequest\x12\r\n\x05state\x18\x01 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x02 \x01(\t\"\xb7\x01\n\x0c\x43hatResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08\x65ndpoint\x18\x02 \x01(\t\x12\x14\n\x0cresponseTime\x18\x03 \x01(\t\x12\x12\n\nstatusCode\x18\x04 \x01(\x05\x12-\n\x04\x64\x61ta\x18\x05 \x03(\x0b\x32\x1f.drrobot.ChatResponse.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xb9\x01\n\rWaterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08\x65ndpoint\x18\x02 \x01(\t\x12\x14\n\x0cresponseTime\x18\x03 \x01(\t\x12\x12\n\nstatusCode\x18\x04 \x01(\x05\x12.\n\x04\x64\x61ta\x18\x05 \x03(\x0b\x32 .drrobot.WaterResponse.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xbc\x01\n\x0c\x42othResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x14\n\x0cresponseTime\x18\x02 \x01(\t\x12.\n\x07results\x18\x03 \x01(\x0b\x32\x1d.drrobot.BothResponse.Results\x1aU\n\x07Results\x12#\n\x04\x63hat\x18\x01 \x01(\x0b\x32\x15.drrobot.ChatResponse\x12%\n\x05water\x18\x02 \x01(\x0b\x32\x16.drrobot.WaterResponse2\xbc\x01\n\x0b\x44octorRobot\x12\x36\n\x07\x41skChat\x12\x14.drrobot.ChatRequest\x1a\x15.drrobot.ChatResponse\x12=\n\x0cPredictWater\x12\x15.drrobot.WaterRequest\x1a\x16.drrobot.WaterResponse\x12\x36\n\x07GetBoth\x12\x14.drrobot.ChatRequest\x1a\x15.drrobot.BothResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'drrobot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATRESPONSE_DATAENTRY']._loaded_options = None
  _globals['_CHATRESPONSE_DATAENTRY']._serialized_options = b'8\001'
  _globals['_WATERRESPONSE_DATAENTRY']._loaded_options = None
  _globals['_WATERRESPONSE_DATAENTRY']._serialized_options = b'8\001'
  _globals['_CHATREQUEST']._serialized_start=26
  _globals['_CHATREQUEST']._serialized_end=74
  _globals['_WATERREQUEST']._serialized_start=76
  _globals['_WATERREQUEST']._serialized_end=122
  _globals['_CHATRESPONSE']._serialized_start=125
  _globals['_CHATRESPONSE']._serialized_end=308
  _globals['_CHATRESPONSE_DATAENTRY']._serialized_start=265
  _globals['_CHATRESPONSE_DATAENTRY']._serialized_end=308
  _globals['_WATERRESPONSE']._serialized_start=311
  _globals['_WATERRESPONSE']._serialized_end=496
  _globals['_WATERRESPONSE_DATAENTRY']._serialized_start=265
  _globals['_WATERRESPONSE_DATAENTRY']._serialized_end=308
  _globals['_BOTHRESPONSE']._serialized_start=499
  _globals['_BOTHRESPONSE']._serialized_end=687
  _globals['_BOTHRESPONSE_RESULTS']._serialized_start=602
  _globals['_BOTHRESPONSE_RESULTS']._serialized_end=687
  _globals['_DOCTORROBOT']._serialized_start=690
  _globals['_DOCTORROBOT']._serialized_end=878
# @@protoc_insertion_point(module_scope)
